### PR TITLE
add semicolon setting

### PR DESCRIPTION
**Pull request by sappharx**

### CODE REVIEW

**Comment by sappharx** [comment]
to run Atom in dev mode for this package/PR:

`apm develop atom-jasmine-es6-snippets`

then

`atom . -d`

open Chrome dev tools if you need

**Comment by Keysox** [comment]
:shipit:

**Comment by sappharx** [comment]
I should use `path.join` instead of string interpolation to avoid any potential cross-platform issues

**Comment by sappharx** [comment]
I may be able to pull out most of the logic in `activate` into its own function, then I can call it in the setting observer so we don't have to wait for a reload for settings to take effect

**Comment by sappharx** [comment]
I can update the snippet files immediately after changing the setting, but Atom does not re-parse the snippet files. For now, it looks like we'll have to live with reloading Atom after changing the settings. I may come back around to this in the future some time.

**Pull request merged**
